local M = {}

-- https://www.nerdfonts.com/cheat-sheet
local nerd_base = {
	Account = "",
	Array = "",
	Boolean = "",
	Bug = "",
	Calendar = "",
	Check = "",
	CheckAll = "",
	Circle = "",
	CircleFilled = "",
	CirclePause = "",
	CircleSlash = "",
	CircleStop = "",
	Class = "ﴯ",
	Collapsed = "",
	Color = "",
	Debug = "",
	History = "",
	IndentGuide = "⎸",
	Interface = "",
	Key = "",
	Keyword = "",
	List = "",
	Method = "",
	Module = "",
	MultiComment = "",
	Namespace = "",
	Notebook = "ﴬ",
	Null = "ﳠ",
	Number = "",
	Object = "",
	Operator = "",
	Package = "",
	Pass = "",
	PassFilled = "",
	Pencil = "",
	Property = "ﰠ",
	Reference = "",
	Separator = "•",
	Snippet = "",
	SignIn = "",
	Space = " ",
	String = "",
	Struct = "פּ",
	Text = "",
	TypeParameter = "",
	Unit = "塞",
	Value = "",
	Variable = "",
	Warning = "",
}

local nerd_solid = {
	Book = "",
	Bookmark = "",
	Bookmarks = "",
	Comment = "",
	Constant = "",
	Constructor = "",
	DiffAdded = "",
	Enum = "",
	EnumMember = "",
	Event = "",
	Expanded = "",
	Field = "ﰠ",
	File = "",
	Files = " ",
	FileBlank = "",
	Folder = "",
	Folders = "",
	Function = "",
	Gear = "",
	GitBranch = "",
	GitCommit = "ﰖ",
	GitCompare = "",
	GitIssue = "",
	GitFolder = "",
	GitPullRequest = "",
	GitRepo = "",
	Info = "",
	Lightbulb = "",
}

local nerd_outline = {
	Bookmark = "",
	Comment = "",
	Info = "",
	Lightbulb = "",
}

M.nerd_solid = vim.tbl_deep_extend("keep", nerd_solid, nerd_base)
M.nerd_outline = vim.tbl_deep_extend("keep", nerd_outline, nerd_base)

return M
